In [1]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [12]:
#2D array - matrices

In [13]:
#To make an matrix, use lists in a list
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
#Create NumPy array, not using python lists
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
#Get even numbers from array
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
#Generate arrays of all zeros
np.zeros(3)

array([ 0.,  0.,  0.])

In [20]:
#Generate 5 rows * 5 columns of all zeros
np.zeros((5,5)) #define tuple

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
#Generate arrays of pure ones
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [23]:
#Generate 3 rows * 4 columns of all ones
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [26]:
#Get 10 evenly spaced points from 0 to 5
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [28]:
#Identity matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [31]:
#Populate array with random samples between 0 and 1
np.random.rand(5) 

array([ 0.80064753,  0.56625097,  0.04936043,  0.10637345,  0.51918282])

In [32]:
#Populate 2-D array with random samples between 0 and 1
np.random.rand(5,5)

array([[ 0.18254402,  0.05983154,  0.31981416,  0.06645847,  0.0957211 ],
       [ 0.55141003,  0.41095874,  0.35826742,  0.64596193,  0.90435405],
       [ 0.91981262,  0.72537778,  0.44633106,  0.93335856,  0.11627802],
       [ 0.40662119,  0.96847666,  0.34942676,  0.55803834,  0.73252853],
       [ 0.70108558,  0.60047793,  0.64268688,  0.84326269,  0.74850935]])

In [35]:
#Populate array with random samples from standard normal distribution centered around 0
np.random.randn(2)

array([-0.37794879, -2.52160313])

In [36]:
#Populate 2-D array with random samples from standard normal distribution centered around 0
np.random.randn(4,4)

array([[-0.91972776, -0.14644046, -0.30982125, -1.22170886],
       [-0.97036082, -1.30994264,  0.67187735, -0.27913113],
       [-1.04588075,  1.94948446, -0.52836837,  1.38263439],
       [-0.35584501,  1.25244891, -0.7608316 ,  0.24932217]])

In [40]:
#Populate array with 10 random integers including 1 (low end) but excluding 100 (high end)
np.random.randint(1,100,10)

array([17, 46, 74, 40, 60, 97, 59, 91, 41, 95])

----

In [41]:
arr = np.arange(25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranarr = np.random.randint(0,50,10)

In [44]:
ranarr

array([10, 26, 49,  7, 16, 10, 22, 42, 17, 44])

In [48]:
#Reshape array to 5*5 matrix
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr.reshape(5,4) #Will result in error because it does not fill up the items in array

ValueError: total size of new array must be unchanged

In [50]:
#Find maximum number
ranarr.max()

49

In [51]:
#Find minimum number
ranarr.min()

7

In [52]:
#Get the index value for maximum number
ranarr.argmax()

2

In [53]:
#Get the index value for minimum number
ranarr.argmin()

3

In [65]:
#Knowing the shape of array
arr.shape #only 1 dimensional

(25,)

In [66]:
arr = arr.reshape(5,5)

In [67]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
arr.shape

(5, 5)

In [69]:
#Return data type in array
arr.dtype

dtype('int32')

In [73]:
from numpy.random import randint #Don't have to type np.random all over again

In [74]:
randint(2,10)

9